# Generated by Django 3.2.9 on 2022-01-05 14:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='photo', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='photo', max_length=255),
        ),
    ]
