# Generated by Django 3.2.9 on 2022-01-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0006_auto_20220105_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
